### PR TITLE
support legacy namespace package mechanism

### PR DESCRIPTION
**Pull request by ofek**

### CODE REVIEW

**Comment by pfmoore** [comment]
Ignore the lint failure, that's my code that's triggering it (I'm deciding if I hate black enough to remove it at the moment).

Can you add some tests for this? I'm particularly interested in tests that show the situation that you're trying to handle here, and what you expect it to do. It looks like you're somehow trying to treat "old-style" namespace packages as if they are new-style ones, which I'm not convinced is the correct behaviour.

(Be careful here, namespace packages are messy - they don't seem to get merged correctly if you have different "parts" of them handled by different import hooks. I may need to go digging in the importlib tests, or even the importlib code itself, to see what's going on here).

**Comment by ofek** [comment]
This PR makes it work now for me and should be alright per https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages

> Note: Because native and pkgutil-style namespace packages are largely compatible, you can use native namespace packages in the distributions that only support Python 3 and pkgutil-style namespace packages in the distributions that need to support Python 2 and 3.

**Comment by pfmoore** [comment]
See [this post on discourse](https://discuss.python.org/t/standardising-editable-mode-installs-runtime-layout-not-hooks/4098/99). What would be installed with this patch is not a namespace package, but rather a normal package which doesn't have the "dynamic recalculation" mechanism of namespaces. I'm not even clear what behaviour it would have. I'm currently trying to write a set of tests that check "install behaviour" for the purposes of validating that redirected modules satisfy those checks, and I'm stuck on what behaviours to require for a namespace package if we deliberately omit considering what happens if `sys.path` gets modified at runtime. Assuming I come up with something, I've no idea at the moment whether this implementation would pass or fail those tests 🙁

I don't want this library to claim to support namespace packages but not deliver the normal functionality of a namespace package. If the discussion on Discourse comes up with a clear definition of what functionality an "editable namespace package" should support, that can be added to the editables PEP and we can look at implementing that (making it clear that it's a limited-functionality emulation).

In the meantime build backends can implement their own handling of namespace packages, we just won't provide pre-packaged support.

**Comment by pfmoore** [comment]
The new API in #7 supersedes this. Namespace packages aren't supported directly, but there's an "add a directory to `sys.path`" mode which gives equivalent functionality to the current setuptools mechanism, so that can be used if needed.

**Comment by pfmoore** [comment]
Hmm, I'm confused as to why this PR seems to be applying against the `redirector` branch rather than against `main`, but as it's no longer relevant, I'm not sure I care.

I'll close this to avoid confusion. Thanks for the contribution, both here and elsewhere. If you feel like there's a better way to support namespace packages with the new API, please feel free to open a new PR!

**Pull request closed without merging**
